version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - add_ssh_keys:
        fingerprints:
          - "3e:f2:5e:9b:d1:7b:6e:49:b5:53:b4:72:a4:cb:fb:51"
      - checkout
      - node/with-cache:
          steps:
            - run: git config user.email "chardevel.a@gmail.com"
            - run: git config user.name "CHARDEVEL Axel"
            - run: npm install
            - run: npm run deploy
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
        filters:
          branches:
            only:
              - master
