version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Create .env.production file with secrets
                command: |
                  echo "SENTRY_DSN=$SENTRY_DSN"
                  echo "SENTRY_DSN=$SENTRY_DSN" >> env.production
                  echo "GA_TRACKING_ID=$GA_TRACKING_ID" >> env.production
                  ls
            - run: |
                npm install
            - run: |
                npm run build
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - add_ssh_keys
      - node/with-cache:
          steps:
            - run:
                name: Create .env.production file with secrets
                command: |
                  echo "SENTRY_DSN=$SENTRY_DSN" >> env.production
                  echo "GA_TRACKING_ID=$GA_TRACKING_ID" >> env.production
                  cat env.production
            - run:
                name: Git configuration
                command: |
                  git config user.email "chardevel.a@gmail.com"
                  git config user.name "CHARDEVEL Axel"
            - run: |
                npm install
            - run: |
                npm run build
            - run: |
                npm run cname
                npm run deploy
workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - deploy:
          filters:
            branches:
              only: master
