version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: |
                npm install
            - run: |
                npm run build
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - add_ssh_keys
      - node/with-cache:
          steps:
            - run: |
                sh """cat <<EOT >> env.production
                    SENTRY_DSN=$SENTRY_DSN
                    GA_TRACKING_ID=$GA_TRACKING_ID
                EOT"""
            - run: |
                npm install
            - run: |
                git config user.email "chardevel.a@gmail.com"
                git config user.name "CHARDEVEL Axel"
            - run: |
                npm run build
            - run: |
                npm run cname
                npm run deploy
workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - deploy:
          filters:
            branches:
              only: master
