version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - add_ssh_keys
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - run: git config user.email "chardevel.a@gmail.com"
            - run: git config user.name "CHARDEVEL Axel"
            - run: npm run cname && npm run deploy
workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master,
                - gh-pages
      - deploy:
          filters:
            branches:
              only: master
